packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@prisma/engines"
  - prisma
  - sharp
allowBuilds:
  "@prisma/engines": true
  prisma: true
  sharp: true
storeDir: /tmp/pnpm-store
confirmModulesPurge: false
